# Generated by Django 2.2.2 on 2019-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(default='dgfrghr', max_length=60),
            preserve_default=False,
        ),
    ]
